### ISSUE TITLE
Date parsing error

### ISSUE THREAD

**Issue by vik78** [gustafl/ExcelLibrary#21]
Hi.
It doesn't parse cells with date and date cell type
for example

![image](https://cloud.githubusercontent.com/assets/13810046/9569381/0de22880-4f72-11e5-93c4-041beaa65561.png)

**Comment by gustafl** [comment]
Thanks for reporting. Both the Date and Time number formats needs special treatment in `Sheet.Open()` to convert them to standard ISO date and times. But this task is dependent on #11.

**Comment by gustafl** [comment]
This should work now.
